version: '1.1'
services:
  app:
    build: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mongodb+srv://admin:admin1234@cluster0.nzzihbr.mongodb.net/?retryWrites=true&w=majority"
